plugins {
	id 'net.fabricmc.fabric-loom' version "1.15-SNAPSHOT"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Sylv"
                url = uri("https://maven.sylv.gay/releases/")
            }
        }

        filter {
            includeGroup("gay.sylv.missingno")
        }
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    runtimeOnly("gay.sylv.missingno:missingno-fix:1.0.0") // Missingno fix
    runtimeOnly("maven.modrinth:sodium:mc26.1.2-0.8.10-fabric")
    runtimeOnly("maven.modrinth:lithium:mc26.1.2-0.24.2-fabric")
    runtimeOnly("maven.modrinth:ferrite-core:9.0.0-fabric")
    runtimeOnly("maven.modrinth:modmenu:18.0.0-alpha.8")
	
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}"}
	}
}