# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1
loader_version=0.19.1

# Mod Properties
mod_version=1.0.0
maven_group=net.justmili.lumynitystudios
archives_base_name=LumynityPlushies

# Dependencies
fabric_api_version=0.146.0+26.1.2